---
conf.py:
  copyright: 2023
  project: mindshape SEO
  version: 3.0
  latex_documents:
  - - Index
      - mindshape_seo.tex
      - mindshape SEO Extension
      - mindshape GmbH
      - manual
  html_theme_options:
    github_repository: mindshape-GmbH/mindshape_seo
    github_branch: master
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - https://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - https://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - https://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
